spring:
  application:
    name: auth-service
  cloud:
    config:
      username: user
      password: password
  config:
    import: configserver:https://user:password@config-icu.herokuapp.com

jasypt:
  encryptor:
    password: jazaradebuggers