spring:
  application:
    name: auth-service
  config:
    import: configserver:https://config-icu.herokuapp.com
    username: user
    password: password

jasypt:
  encryptor:
    password: jazaradebuggers