spring:
  application:
    name: auth-service
  config:
    import: configserver:https://user:password@icu-config.herokuapp.com

jasypt:
  encryptor:
    password: jazaradebuggers

swagger:
  config:
    refreshrate: 5000

app.firebase-configuration-file: icu-project-abdc8-firebase-adminsdk-osgg9-b484722fa6.json

app-defaults:
  defaults:
    topic: 'all'
    title: 'Alert!'
    body: 'Watch out ! Click to see details'
    image: 'link_to_image'
    token: 'dcrq8MJFRnGrltu_EedHUm:--'
    carid: '23'
    route: '/camera/id'
    click_action: 'FLUTTER_NOTIFICATION_CLICK'
